### ISSUE TITLE
Failure to install

### ISSUE THREAD

**Issue by ms-balzer** [JEFworks-Lab/veloviz#10]
Installation via 
require(devtools)
devtools::install_github('JEFworks-Lab/veloviz')

gives me 

Error: Failed to install 'unknown package' from GitHub:
  HTTP error 404.
  No commit found for the ref master

  Did you spell the repo owner (`JEFworks-Lab`) and repo name (`veloviz`) correctly?
  - If spelling is correct, check that you have the required permissions to access the repo.

I see this has been posted before. Any solution much appreciated!

**Comment by LylaAtta123** [comment]
Hello, 

Could you please try installing with `remotes` as detailed [here](https://github.com/JEFworks-Lab/veloviz/issues/5#issuecomment-758002833)? 

Lyla

**Comment by ms-balzer** [comment]
Installing with remotes worked, thank you!
