### ISSUE TITLE
Docker container for Veloviz

### ISSUE THREAD

**Issue by zakiF** [JEFworks-Lab/veloviz#16]
Hi, 

Congratulations on the publication of VeloViz! And many thanks for providing well-documented tutorials. With the excellent tutorials, I am very excited to give VeloViz a try. I  managed to install VeloVis. However, I could not get velocyto.R installed on my desktop (despite trying for a few days now). 

I wonder if the authors would be so kind as to provide a docker installation of Veloviz with the required dependencies. Something similar to how Velocyto.R provides a docker installation https://github.com/velocyto-team/velocyto.R

I think it would help tremendously. 

Best,
Zaki

**Comment by JEFworks** [comment]
Dear Zaki,

Thanks for your interest in using VeloViz and for the suggestion. 

Given that your challenges with installation are with velocyto.R, it may be more appropriate to bring this to the attention of the velocyto.R developers. 

You may also consider installing VeloViz directly within the Docker container for velocyto.R. Alternatively, you can always save the output of velocyto.R as an RData/RDS after running it from within the Docker container and then continue working with that RData/RDS file where you have successfully installed VeloViz.

Hope this helps,
Jean
