### ISSUE TITLE
Error in buildVeloviz

### ISSUE THREAD

**Issue by yen-tran-91** [JEFworks-Lab/veloviz#9]
Hi, 

I am trying to run buidVeloviz function with input from RNAvelocity as shown in vignette 
veloviz = buildVeloviz(
  curr = curr, proj = proj,
  normalize.depth = TRUE,
  use.ods.genes = TRUE,
  alpha = 0.05,
  pca = FALSE,
  nPCs = 10,
  center = TRUE,
  scale = TRUE,
  k = 3,
  similarity.threshold = 0.25,
  distance.weight = 1,
  distance.threshold = 0.5,
  weighted = TRUE,
  seed = 0,
  verbose = FALSE
)
However, I keep receiving below error:
Error in which(nn_dists_i == min(nn_dists_i), na.rm = TRUE) : 
  unused argument (na.rm = TRUE)

Do you know what causes the error? Thank you very much!

**Comment by LylaAtta123** [comment]
Hello, 

Yes, this was a bug in an earlier commit. Could you please try reinstalling and see if you still get the error? 

Thanks! 
Lyla
